Description: >
  This template illustrates reference architecture for Deployment on ECS.

Parameters:
  TemplateBucket:
    Type: String
    Description: >
      S3 Bucket used for nested templates
    Default: sgas.botkit.demo

  GitHubUser:
    Type: String
    Default: YourGithubUsernameHere

  GitHubRepo:
    Type: String
    Default: botkit

  GitHubBranch:
    Type: String
    Default: master

  GitHubToken:
    Type: String
    Default: YourGithubTokenHere

  HostedZoneName:
    Type: String
    Default: YourHostedZoneNameHere

  Stack:
    Type: String
    Default: Botkit

  DBPassword:
    Default: password
    NoEcho: true
    Description: testdb admin account password
    Type: String
    MinLength: 6
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.

  Hostname:
    Type: String
    Default: botkit

  certificateArn:
    Type: String
    Default: YourCertificateARnHere

  clientId:
    Type: String
    Default: YourSlackClientIdHere

  clientSecret:
    Type: String
    Default: YourSlackClientSecretHere

  lexBotName:
    Type: String
    Default: botkit

  VpcId:
    Type: String
    Default: YourVpcIdHere

  VpcCIDR:
    Type: String
    Default: YourVpcCIDRHere

  Subnet1:
    Type: String
    Default: YourSubnet1Here

  Subnet2:
    Type: String
    Default: YourSubnet2Here

  ClusterCount:
    Type: String
    Default: "2"

  Filename:
    Type: String
    Default: lambda_function.zip

Resources:
  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/test-deployment-pipeline.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket
        Subnet1: !Ref Subnet1
        Subnet2: !Ref Subnet2
        VpcId: !Ref VpcId
        VpcCIDR: !Ref VpcCIDR
        Stack: !Ref Stack
        HostedZoneName: !Ref HostedZoneName
        Hostname: !Ref Hostname
        certificateArn: !Ref certificateArn
        clientId: !Ref clientId
        clientSecret: !Ref clientSecret
        DBPassword: !Ref DBPassword
        lexBotName: !Ref lexBotName
        ClusterCount: !Ref ClusterCount
        Filename: !Ref Filename
        GitHubUser: !Ref GitHubUser
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken

Outputs:
 PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl



